BaseUrl= "https://sieverapp.com/"
LanguageCode= "en-us"
Title= "Siever App"
# paginate = 5
DisqusShortname = ""
Copyright = "© 2017"
canonifyurls = true
theme = "casper"

[[menu.main]]
  name = "Home"
  weight = -120
  identifier = "home"
  url = "/"
  
[params]
  description = "SMS Spam Blocker for iOS"

  myApps = "The first real SMS Spam blocker for iOS"
  myApp1Image = "images/app-siever.png"
  myApp1Name = "Siever"
  myApp1Url = "http://apple.co/2jsfavB"

  cover = "images/cover.jpg"
  author = "Jan Čislinský"
  bio= "The first real SMS Spam blocker for iOS"
  authorlocation = ""
  authorwebsite = ""
  
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-88903646-4"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..." 
  # githubName = "jcislinsky"
  # twitterName = "jcislinsky"
  # facebookName = ""
  # linkedinName = "jcislinsky"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false